### PR TITLE
PZ1 emulation updated

### PR DESCRIPTION
**Pull request by NollKollTroll**
More comments, more defines, code that works closer to the real thing.
Hopefully not out of line style-wise.
My first pull request ever, be gentle :)

### CODE REVIEW

**Comment by EtchedPixels** [comment]
Some minor comments
- uint8_t is much slower than unsigned on many processors so I try and use it for stuff that really is 8bit not for internal calculations
- the two routines for testing if a char is ready and getting it shouldn't be changed in behaviour or signature as they are expected to have their existing behaviour by all the hardware emulation drivers, so will cause problems if changed and you add a real uart or emulation of one
- your disk change to if / else is usually worse code than clearing it and setting it on the unlikely code path. Not really important in this case but something to know and one the compiler can't optimize itself due to sequence rules in C


otherwise looks good.

**Comment by NollKollTroll** [comment]
I updated according to your comments, I think these changes are included in this pull request now and ready to be merged.

**Comment by NollKollTroll** [comment]
I added the latest code to fix ROM/RAM and some more I/O-ports. Needs a Fuzix update as well to be able to run correctly, added pull request there.

**Comment by EtchedPixels** [comment]
Thanks

**Pull request merged**
