### PR TITLE
RC2014 SIO: Increase input buffer queue from 2 chars to 60 chars

### PR DESCRIPTION
**Pull request by vipoo**
Hi again,

This is a small PR - i seperated it from the Makefile changes.

When i was running the RC2014 emualtor thru a detached screen session - so that my automated tests scripts could send keys to the session - i noticed that input characters would be dropped.  

This was due to the emulator only having a 2 byte buffer for the input stream.  

This PR increases the buffer to 60 bytes.

Cheers
Dean

### CODE REVIEW

**Comment by EtchedPixels** [comment]
The hardware only has a 2 byte buffer so the emulation is correct. It is properly emulating the fact that if you fire characters at it really fast it drops bytes.

If you are doing automated tests then you either want to use small delays or possibly it'll be ok to run with "-f" so you are running on an emulated insanely fast processor.

**Comment by vipoo** [comment]
That makes total sense - i will have another go

**Comment by EtchedPixels** [comment]
I've been thinking about this and I have another suggestion that might make more sense

Instead of messing with that part of the UART emulation how about changing the receive code to note check for and queue a byte if the UART in question has RTS/CTS flow control enabled and asserted. That ought to accurately model a real system with flow control on and overrun ?

**Comment by vipoo** [comment]
Hi ya, Yep – I had looked at that a few weeks ago – But I got an issue with interrupts not getting processed right – and all keyboard input just stops getting process -its like the interrupts don’t get processed anymore – I did a lot of logging and cant remember specific – but the sequence of events and interrupts did not seem to flow quite right.  There is also a lot I do not understand – so I probably need to have another go. I have got a bit of a hack running at the moment, - where on input char ready, I check the size of the buffer – and only submit if there is room – it works for my specific need – and char input runs very fast now – but solution probably not suited for others.  (https://github.com/vipoo/RC2014/commit/315ca9e938ea5412175bf2eff2a541ad08e84bf6) But this has allowed me to reliably run automated tests scripts for some changes I have been doing to RomWBW. (If you are interested, the test scripts/framework is in the repo: https://github.com/vipoo/RomWBW-Env – with the file: `test-cpm-hbios` the main script.  This script runs a session of RC2014 in a dedicated screen (to capture output) – injecting strings from specific test scripts files – and verifying specific output.  You can see output of tests runs on my travis site: https://travis-ci.org/github/vipoo/RomWBW-Env/jobs/679378106) I do hope to have another go – and see if I can figure it out properly. CheersDean   Sent from Mail for Windows 10 From: EtchedPixelsSent: Sunday, 26 April 2020 4:37 AMTo: EtchedPixels/RC2014Cc: Dean Netherton; State changeSubject: Re: [EtchedPixels/RC2014] RC2014 SIO: Increase input buffer queue from 2 chars to 60 chars (#16) I've been thinking about this and I have another suggestion that might make more senseInstead of messing with that part of the UART emulation how about changing the receive code to note check for and queue a byte if the UART in question has RTS/CTS flow control enabled and asserted. That ought to accurately model a real system with flow control on and overrun ?—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

**Pull request closed without merging**
